"""parent-note

Revision ID: 03a9a1f818ce
Revises: 8113ce41ca48
Create Date: 2025-11-12 03:57:52.599463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a9a1f818ce'
down_revision: Union[str, Sequence[str], None] = '8113ce41ca48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_note', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_note', 'item_note', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_note', type_='foreignkey')
    op.drop_column('item_note', 'parent_id')
    # ### end Alembic commands ###
