"""item-type-field-ctrl

Revision ID: 28404275a407
Revises: ae238887cfa3
Create Date: 2025-11-08 17:06:06.816962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28404275a407'
down_revision: Union[str, Sequence[str], None] = 'ae238887cfa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type_field', sa.Column('contral_id', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_type_field', 'contral_id')
    # ### end Alembic commands ###
