"""a-source-data

Revision ID: 7d65628a346e
Revises: a6ff51164d3e
Create Date: 2025-11-17 20:29:06.127750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d65628a346e'
down_revision: Union[str, Sequence[str], None] = 'a6ff51164d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_attachment', sa.Column('source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_attachment', 'source_data')
    # ### end Alembic commands ###
