"""sort

Revision ID: 8e02024f4ef2
Revises: 1b0f7aae4d28
Create Date: 2025-11-08 15:27:44.539682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e02024f4ef2'
down_revision: Union[str, Sequence[str], None] = '1b0f7aae4d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type_field', sa.Column('sort', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_type_field', 'sort')
    # ### end Alembic commands ###
