"""note-attachment2

Revision ID: a35c5a9c7332
Revises: d4cc7355ca01
Create Date: 2025-11-17 09:21:39.659549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a35c5a9c7332'
down_revision: Union[str, Sequence[str], None] = 'd4cc7355ca01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_attachment', 'key',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('item_note', 'key',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_note', 'key',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('item_attachment', 'key',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
