"""field-label-null

Revision ID: ae238887cfa3
Revises: 8e02024f4ef2
Create Date: 2025-11-08 16:58:22.284171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae238887cfa3'
down_revision: Union[str, Sequence[str], None] = '8e02024f4ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field', sa.Column('label', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field', 'label')
    # ### end Alembic commands ###
