"""item-type-field-ctrl2

Revision ID: b536f0e0934e
Revises: 28404275a407
Create Date: 2025-11-08 17:07:42.023751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b536f0e0934e'
down_revision: Union[str, Sequence[str], None] = '28404275a407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type_field', sa.Column('control_id', sa.SmallInteger(), nullable=True))
    op.drop_column('item_type_field', 'contral_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type_field', sa.Column('contral_id', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('item_type_field', 'control_id')
    # ### end Alembic commands ###
