"""note-attachment

Revision ID: d4cc7355ca01
Revises: 03a9a1f818ce
Create Date: 2025-11-17 09:21:01.279994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cc7355ca01'
down_revision: Union[str, Sequence[str], None] = '03a9a1f818ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_attachment', sa.Column('note_id', sa.Integer(), nullable=True))
    op.add_column('item_attachment', sa.Column('key', sa.UUID(), nullable=True))
    op.add_column('item_attachment', sa.Column('version', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item_attachment', 'item_note', ['note_id'], ['id'])
    op.add_column('item_note', sa.Column('key', sa.UUID(), nullable=True))
    op.add_column('item_note', sa.Column('version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_note', 'version')
    op.drop_column('item_note', 'key')
    op.drop_constraint(None, 'item_attachment', type_='foreignkey')
    op.drop_column('item_attachment', 'version')
    op.drop_column('item_attachment', 'key')
    op.drop_column('item_attachment', 'note_id')
    # ### end Alembic commands ###
